{% set name = "rapidcheck" %}
{% set version = "2023.4.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

# rapidcheck does not have tags or release.
# For now, we version it with the date of a commit of choice.
# See: https://github.com/emil-e/rapidcheck/issues/306
source:
  url: https://github.com/emil-e/rapidcheck/archive/a5724ea5b0b00147109b0605c377f1e54c353ba2.tar.gz
  sha256: 9a754942f99027c66c0aed14a684cd4a36b28ab232d9079473d427d09af57871

build:
  number: 2

requirements:
  build:
    - make  # [unix]
    - {{ compiler('cxx') }}
    - cmake
  host:
    - gtest

test:
  commands:
    - test -e ${PREFIX}/include/rapidcheck.h  # [unix]
    - test -e ${PREFIX}/include/rapidcheck/Show.hpp  # [unix]
    - test -e ${PREFIX}/share/rapidcheck/cmake/rapidcheckConfig.cmake  # [unix]
    - test -e ${PREFIX}/lib/librapidcheck.so  # [linux]
    - if not exist %LIBRARY_PREFIX%\include\rapidcheck.h (exit 1)  # [win]



about:
  home: https://github.com/emil-e/rapidcheck
  summary: 'RapidCheck is a C++ framework for property based testing inspired by QuickCheck and other similar frameworks.'
  description: |
    RapidCheck is a C++ framework for property based testing inspired by QuickCheck and other similar frameworks. 
    In property based testing, you state facts about your code that given certain precondition should always be true.
    RapidCheck then generates random test data to try and find a case for which the property doesn't hold. 
    If such a case is found, RapidCheck tries to find the smallest case (for some definition of smallest) 
    for which the property is still false and then displays this as a counterexample. 
    For example, if the input is an integer, RapidCheck tries to find the smallest integer for which the property is false.

  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  doc_url: https://github.com/emil-e/rapidcheck/blob/master/doc/user_guide.md
  dev_url: https://github.com/emil-e/rapidcheck

extra:
  recipe-maintainers:
    - DerThorsten
    - jjerphan
